version: '3.8'
services:
  vulnscanner:
    build: .
    container_name: vulnscanner-pro
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
